Update launch-delayed-jiva-rep-with-ip

diff --git a/scripts/launch-delayed-jiva-rep-with-ip b/scripts/launch-delayed-jiva-rep-with-ip
--- a/scripts/launch-delayed-jiva-rep-with-ip
+++ b/scripts/launch-delayed-jiva-rep-with-ip
@@ -96,8 +96,8 @@ _stop() {
 }
 
 echo "Trapping SIGINT, SIGTERM and SIGKILL"
-trap _stop SIGINT
-trap _stop SIGTERM
+#trap _stop SIGINT
+#trap _stop SIGTERM
 
 echo "Starting container $JIVA_REP_NAME after 60s"
 sleep 60
@@ -124,4 +124,4 @@ fi
 echo "Waiting for container $JIVA_REP_NAME ($CONTAINER_ID) to finish"
 PID=$(ps aux | grep "docker-containerd-shim $CONTAINER_ID" | grep -v "grep" | awk '{print $2}')
 anywait $PID
-cleanup
+#cleanup
